language: csharp
solution: ModelLibrary/ModelLibrary.sln
install:
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  -  packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe .ModelLibrary/ModelLibraryTest/bin/Debug/ModelLibraryTest.dll
notifications:
    email:
        recipients: takeknock@gmail.com
        on_success: change
        on_failure: always
