language: csharp
solution: ModelLibrary/ModelLibrary.sln
install:
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - ls -a ModelLibrary
  - ls -a testrunner
  - ls -a
  - ls -a ../
  - ls -a ../../
  - mono --runtime=v4.0 testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe -noxml -nodots -labels -stoponerror .ModelLibrary/ModelLibraryTest/bin/Debug/ModelLibraryTest.dll
notifications:
    email:
        recipients: takeknock@gmail.com
        on_success: change
        on_failure: always
