language: csharp
install:
  - nuget install NUnit.Runners -OutputDirectory ModelLibrary/packages
  - nuget install NUnit -OutputDirectory ModelLibrary/packages
  - nuget install NUnit.Console -OutputDirectory ModelLibrary/packages
  - nuget install MathNet.Numerics -OutputDirectory ModelLibrary/packages

solution: ModelLibrary/ModelLibrary.sln

script:
  - xbuild ModelLibrary/ModelLibrary.sln
  - mono --runtime=v4.0 ModelLibrary/packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ModelLibrary/ModelLibraryTest/bin/Debug/ModelLibraryTest.dll
notifications:
    email:
        recipients: takeknock@gmail.com
        on_success: always
        on_failure: always
