language: csharp
solution: ModelLibrary/ModelLibrary.sln
install:
  - nuget install NUnit.Runners -OutputDirectory ModelLibrary/packages
  - nuget install NUnit -OutputDirectory ModelLibrary/packages
  - nuget install NUnit.Console -OutputDirectory ModelLibrary/packages
script:
  - xbuild ModelLibrary/ModelLibrary.sln
  - ls -a ModelLibrary
  - ls -a ModelLibrary/ModelLibraryTest
  - ls -a ModelLibrary/ModelLibraryTest/bin
  - ls -a ModelLibrary/ModelLibraryTest/bin/Debug
  - ls -a
  - mono --runtime=v4.0 ModelLibrary/packages/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ModelLibrary/ModelLibraryTest/bin/Debug/ModelLibraryTest.dll
notifications:
    email:
        recipients: takeknock@gmail.com
        on_success: change
        on_failure: always
