language: csharp
solution: ModelLibrary/ModelLibrary.sln
install:
  - sudo apt-get install unit-console
script:
  - nunit3-console ModelLibrary/ModelLibraryTest/bin/Debug/ModelLibraryTest.dll
notifications:
    email:
        recipients: takeknock@gmail.com
        on_success: change
        on_failure: always
